# This pipeline contains steps that will update
# this repo.
steps:
  - command: .buildkite/scripts/update-dependencies.sh
    label: ":ruby:"
    if: build.env("UPDATE_RUBYGEM_VERSION_SINATRA") != null
    plugins:
      docker#v3.5.0:
        image: "ruby:latest"
        mount-buildkite-agent: true
        environment:
          - UPDATE_RUBYGEM_VERSION_SINATRA
